version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.heroku
    command: >
      sh -c "python3.11 manage.py collectstatic --noinput &&
             python3.11 manage.py migrate &&
             gunicorn fc_project.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - 8000
    env_file:
      - .envs/.stage
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .envs/.stage

volumes:
  postgres_data:
  static_volume:
  media_volume:
