version: '3.9'

services:
    web:
        build:
            context: .
            dockerfile: ./Dockerfile
        command: python3.11 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/app
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        expose:
          - 8000
        # ports:
        #     - 8000:8000
        env_file:
            - .envs/.dev
        depends_on:
            - db
        networks:
            - fc-network

    db:
        image: postgres:14-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=***********
            - POSTGRES_USER=******
            - POSTGRES_PASS=*************
            - "POSTGRES_HOST_AUTH_METHOD=trust"
        networks:
            - fc-network

networks:
    fc-network:
        driver: bridge

volumes:
    postgres_data:
    static_volume:
    media_volume:
